package cc.cc1234.dao.mapper;

import cc.cc1234.dao.model.OrderEntity;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.EnumTypeHandler;
import org.apache.ibatis.type.JdbcType;

public interface OrderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Sep 11 17:41:53 CST 2021
     */
    @Delete({
        "delete from `order`",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Sep 11 17:41:53 CST 2021
     */
    @Insert({
        "insert into `order` (id, user_id, ",
        "order_no, `status`, ",
        "create_at, update_at)",
        "values (#{id,jdbcType=BIGINT}, #{userId,jdbcType=BIGINT}, ",
        "#{orderNo,jdbcType=VARCHAR}, #{status,jdbcType=TINYINT,typeHandler=org.apache.ibatis.type.EnumTypeHandler}, ",
        "#{createAt,jdbcType=TIMESTAMP}, #{updateAt,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Sep 11 17:41:53 CST 2021
     */
    @InsertProvider(type=OrderEntitySqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Sep 11 17:41:53 CST 2021
     */
    @Select({
        "select",
        "id, user_id, order_no, `status`, create_at, update_at",
        "from `order`",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="order_no", property="orderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", typeHandler=EnumTypeHandler.class, jdbcType=JdbcType.TINYINT),
        @Result(column="create_at", property="createAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_at", property="updateAt", jdbcType=JdbcType.TIMESTAMP)
    })
    java.util.Optional<OrderEntity> selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Sep 11 17:41:53 CST 2021
     */
    @UpdateProvider(type=OrderEntitySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Sat Sep 11 17:41:53 CST 2021
     */
    @Update({
        "update `order`",
        "set user_id = #{userId,jdbcType=BIGINT},",
          "order_no = #{orderNo,jdbcType=VARCHAR},",
          "`status` = #{status,jdbcType=TINYINT,typeHandler=org.apache.ibatis.type.EnumTypeHandler},",
          "create_at = #{createAt,jdbcType=TIMESTAMP},",
          "update_at = #{updateAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OrderEntity record);
}