package cc.cc1234.dao.model;

import cc.cc1234.dao.enums.Gender;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Database Table Remarks:
 *   Users and global privileges
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 */
@Data
public class UserEntity {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sat Oct 02 10:48:46 CST 2021
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Sat Oct 02 10:48:46 CST 2021
     */
    private String username;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbg.generated Sat Oct 02 10:48:46 CST 2021
     */
    private Gender gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_at
     *
     * @mbg.generated Sat Oct 02 10:48:46 CST 2021
     */
    private LocalDateTime createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_at
     *
     * @mbg.generated Sat Oct 02 10:48:46 CST 2021
     */
    private LocalDateTime updateAt;
}